refresh_scenes:
  fields:
    device_id:
      required: false
      example: "AA:BB:CC:DD:EE:FF:00:11"
      selector:
        device:
          integration: govee

set_segment_color:
  fields:
    device_id:
      required: true
      example: "AA:BB:CC:DD:EE:FF:00:11"
      selector:
        device:
          integration: govee
    segments:
      required: true
      example: "[0, 1, 2]"
      selector:
        object:
    rgb_color:
      required: true
      example: "[255, 0, 0]"
      selector:
        color_rgb:
